# -*- coding: utf-8 -*-
"""Ruby Briggs -  GenAI Data Analysis Assistant.ipynb

Automatically generated by Colab.

"""

pip install transformers torch gradio

from transformers import pipeline
import spacy
import pandas as pd
import gradio as gr
from sklearn.linear_model import LinearRegression

import warnings
warnings.filterwarnings('ignore')

# Load pre-trained Hugging Face model for text classification
classifier = pipeline('zero-shot-classification', model="facebook/bart-large-mnli")

def classify_prompt(prompt):
    labels = ["descriptive_statistics", "correlation", "regression", "others"]
    result = classifier(prompt, candidate_labels=labels)
    return result['labels'][0]  # Return the highest scored label

nlp = spacy.load("en_core_web_sm")

def extract_variables(prompt):
    doc = nlp(prompt)
    variables = [ent.text for ent in doc.ents if ent.label_ == "GPE" or ent.label_ == "ORG"]  # Customize for variables
    if len(variables) == 0:
        return None
    return variables

def load_data(file):
    if not file.name.endswith('.csv'):
        raise ValueError("Please upload a CSV file.")
    return pd.read_csv(file.name)  # Use file.name to read the file

def get_columns(df):
    return df.columns.tolist()

def descriptive_statistics(df, variables):
    return df[variables].describe()

def correlation(df, variables):
    return df[variables].corr()

def regression(df, dependent_var, independent_vars):
    X = df[independent_vars]
    y = df[dependent_var]
    model = LinearRegression()
    model.fit(X, y)
    return model.coef_, model.intercept_

def analyze_data(file, prompt):
    # Step 1: Classify the prompt
    analysis_type = classify_prompt(prompt)

    # Step 2: Extract variables from the prompt
    variables = extract_variables(prompt)
    if variables is None:
        return "Please specify the variables for analysis."

    # Step 3: Load the data and extract columns
    try:
        df = load_data(file)
    except ValueError as e:
        return str(e)

    columns = get_columns(df)

    if set(variables).issubset(columns):
        if analysis_type == "descriptive_statistics":
            result = descriptive_statistics(df, variables)
        elif analysis_type == "correlation":
            result = correlation(df, variables)
        elif analysis_type == "regression":
            result = regression(df, variables[0], variables[1:])
        else:
            result = "Analysis type not recognized."
    else:
        return "Some variables not found in the dataset."

    return result

# Create Gradio Interface
interface = gr.Interface(fn=analyze_data,
                         inputs=[gr.File(label="Upload CSV File"), gr.Textbox(label="Analysis Prompt")],
                         outputs="text",
                         title = "Gen AI Data Analysis Assistant")

interface.launch(debug = True)

